version: "3"

services:
  scalaris1:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.11
    image: scalaris:latest
    container_name: scalar-consensus1
    hostname: scalaris1
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error,scalaris::consensus_handler=debug
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/files/scalaris1-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - ${PATH_SCALARIS}/db1:/opt/scalaris/db:rw
    command:
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml"
      ]
    ports:
      - "8081:8080"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  scalaris2:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.12
    image: scalaris:latest
    container_name: scalar-consensus2
    hostname: scalaris2
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/files/scalaris2-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - ${PATH_SCALARIS}/db2:/opt/scalaris/db:rw
    command:
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml"
      ]
    ports:
      - "8082:8080"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  scalaris3:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.13
    image: scalaris:latest
    container_name: scalar-consensus3
    hostname: scalaris3
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/files/scalaris3-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - ${PATH_SCALARIS}/db3:/opt/scalaris/db:rw
    command:
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml"
      ]
    ports:
      - "8083:8080"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  scalaris4:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.14
    image: scalaris:latest
    container_name: scalar-consensus4
    hostname: scalaris4
    environment:
      - CONSENSUS=mysticeti
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/files/scalaris4-8080.yaml:/opt/scalaris/config/scalaris.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - ${PATH_SCALARIS}/db4:/opt/scalaris/db:rw
    command:
      [
        "/usr/local/bin/scalaris",
        "--config-path",
        "/opt/scalaris/config/scalaris.yaml"
      ]
    ports:
      - "8084:8080"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"

  execution1:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.21
    image: scalar/execution:latest
    container_name: scalar-execution1
    hostname: execution1
    environment:
      - CONSENSUS_ADDR=http://scalaris1:8080
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_core::consensus_handler=debug,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/files/scalaris1-8080.yaml:/opt/scalar/config/scalaris.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - ${PATH_SCALAR_DB}/db1:/opt/scalar/db:rw
    command:
      [
        "/usr/local/bin/scalar",
        "--config-path",
        "/opt/scalar/config/scalaris.yaml"
      ]
    # restart: on-failure
    restart: no
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  execution2:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.22
    image: scalar/execution:latest
    container_name: scalar-execution2
    hostname: execution2
    environment:
      - CONSENSUS_ADDR=http://scalaris2:8080
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/files/scalaris2-8080.yaml:/opt/scalar/config/scalaris.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalaris/config/genesis.blob:ro
      - ${PATH_SCALAR_DB}/db2:/opt/scalar/db:rw
    command:
      [
        "/usr/local/bin/scalar",
        "--config-path",
        "/opt/scalar/config/scalaris.yaml"
      ]
    # restart: on-failure
    restart: no
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  fullnode:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.25
    image: scalar/execution:latest
    #image: mysten/sui-node:mainnet
    hostname: fullnode
    container_name: fullnode
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug,sui_core=debug,sui_network=debug,sui_node=debug,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ${PATH_SCALARIS_GENESIS}/static/fullnode.yaml:/opt/scalar/config/fullnode.yaml:ro
      - ${PATH_SCALARIS_GENESIS}/files/genesis.blob:/opt/scalar/config/genesis.blob:ro
      - ${PATH_SCALAR_DB}/fullnode:/opt/scalar/db:rw
    command:
      [
        "/usr/local/bin/scalar",
        "--config-path",
        "/opt/scalar/config/fullnode.yaml"
      ]
    ports:
      - 9000:9000
      - 9184:9184
    restart: no
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  tool:
    networks:
      scalar-network:
        ipv4_address: 10.0.10.30
    #image: docker.io/mysten/sui-tools:mainnet-v1.19.1
    image: scalar/sui-tools
    hostname: client
    container_name: client
    command: sleep infinity
    volumes:
      - ./sui_config:/root/.sui/sui_config
    restart: no
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
networks:
  scalar-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
