version: "3"

services:
  validator1-${GIT_SHA}:
    image: scalaris/consensus-node:${GIT_SHA}
    container_name: validator1-${GIT_SHA}
    hostname: validator1-${GIT_SHA}
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/validator1-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db1:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml"
      ]
    restart: on-failure
    ports:
      - 8081:8080
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"

  validator2-${GIT_SHA}:
    image: scalaris/consensus-node:${GIT_SHA}
    container_name: validator2-${GIT_SHA}
    hostname: validator2-${GIT_SHA}
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/validator2-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db2:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml"
      ]
    restart: on-failure
    ports:
      - 8082:8080
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
        
  validator3-${GIT_SHA}:
    image: scalaris/consensus-node:${GIT_SHA}
    container_name: validator3-${GIT_SHA}
    hostname: validator3-${GIT_SHA}
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/validator3-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db3:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml"
      ]
    restart: on-failure
    ports:
      - 8083:8080
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"


  validator4-${GIT_SHA}:
    image: scalaris/consensus-node:${GIT_SHA}
    container_name: validator4-${GIT_SHA}
    hostname: validator4-${GIT_SHA}
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/files/validator4-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db4:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml"
      ]
    restart: on-failure
    ports:
      - 8084:8080
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"

  fullnode1-${GIT_SHA}:
    image: scalaris/consensus-node:${GIT_SHA}
    hostname: fullnode1-${GIT_SHA}
    container_name: fullnode1-${GIT_SHA}
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
    volumes:
      - ./genesis/static/fullnode.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db5:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/fullnode.yaml"
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"

  stress-${GIT_SHA}:
    image: stress:${GIT_SHA}
    container_name: stress-${GIT_SHA}
    environment:
      - RUST_LOG=info
      - STARTUP_DELAY_SECONDS=5
      - STRESS_STAGGERED_START_MAX_MULTIPLIER=0
      - FULLNODE_RPC_ADDRESS=fullnode1-${GIT_SHA}:9000
      - USE_FULLNODE_FOR_RECONFIG=false
      - PRIMARY_GAS_OWNER=0xd59d79516a4ed5b6825e80826c075a12bdd2759aaeb901df2f427f5f880c8f60
      - GENESIS_BLOB_PATH=/opt/sui/config/genesis.blob
      - KEYSTORE_PATH=/opt/sui/config/sui.keystore
      - STRESS_TARGET_QPS=10
      - STRESS_SHARED_COUNTER=1
      - STRESS_TRANSFER_OBJECT=1
      - STRESS_DELEGATION=0
      - BATCH_PAYMENT=1
      - BATCH_PAYMENT_SIZE=100
      - STRESS_ADVERSARIAL=0
    volumes:
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - ./genesis/static/sui.keystore:/opt/sui/config/sui.keystore:ro
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"