version: "3.9"
services:
  reth:
    build:
      context: ../
      dockerfile: ./docker/reth.Dockerfile
    image: reth-client
    container_name: reth-client
    restart: unless-stopped
    ports:
      - "30303:30303" 
      - "30303:30303/udp"
      - "8545-8546:8545-8546"
      - "9001:9001"
